spring:
  application:
    name: api-gateway
  cloud:
    gateway:
      server:
        webmvc:
          routes:
            - id: auth-service
              uri: lb://auth-service
              predicates:
                - Path=/api/v1/auth/**
            - id: clients-service
              uri: lb://clients-service
              predicates:
                - Path=/api/v1/clientes/**
            - id: auth-service-openapi
              uri: lb://auth-service
              predicates:
                - Path=/auth/v3/api-docs
              filters:
                - SetPath=/v3/api-docs
            - id: clients-service-openapi
              uri: lb://clients-service
              predicates:
                - Path=/clients/v3/api-docs
              filters:
                - SetPath=/v3/api-docs
            - id: paquetes-service
              uri: lb://paquetes-service
              predicates:
                - Path=/api/v1/paquetes/**,/api/v1/categorias/**
              filters:
                - AddRequestHeader=X-Source, api-gateway
            - id: paquetes-service-openapi
              uri: lb://paquetes-service
              predicates:
                - Path=/paquetes/v3/api-docs
              filters:
                - SetPath=/v3/api-docs

server:
  port: 8080

resilience4j:
  circuitbreaker:
    instances:
      auth-service:
        sliding-window-size: 5
        failure-rate-threshold: 50
        wait-duration-in-open-state: 10s
        permitted-number-of-calls-in-half-open-state: 3
        slow-call-duration-threshold: 2s
        slow-call-rate-threshold: 50
      clients-service:
        sliding-window-size: 5
        failure-rate-threshold: 50
        wait-duration-in-open-state: 10s
        permitted-number-of-calls-in-half-open-state: 3
        slow-call-duration-threshold: 2s
        slow-call-rate-threshold: 50
      paquetes-service:
        sliding-window-size: 5
        failure-rate-threshold: 50
        wait-duration-in-open-state: 10s
        permitted-number-of-calls-in-half-open-state: 3
        slow-call-duration-threshold: 2s
        slow-call-rate-threshold: 50

management:
  endpoints:
    web:
      exposure:
        include: health,info,circuitbreakers
  endpoint:
    health:
      show-details: always
  circuitbreakers:
    enabled: true

springdoc:
  swagger-ui:
      urls:
        - name: auth-service
          url: /auth/v3/api-docs
        - name: clients-service
          url: /clients/v3/api-docs
        - name: paquetes-service
          url: /paquetes/v3/api-docs

eureka:
  client:
    register-with-eureka: true
    fetch-registry: true
    initial-instance-info-replication-interval-seconds: 5
    instance-info-replication-interval-seconds: 10
